#for lesson 7

server:
  port: 8180
  servlet:
    context-path: /springtest
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=lesson7
    username: postgre
    password: postgre

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
    open-in-view: false
