server:
  port: 8180
  servlet:
    context-path: /springtest
#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=lesson7
#    username: postgre
#    password: postgre
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQL94Dialect
#    open-in-view: false

spring:
  datasource:
    #     driver-class-name: org.postgresql.Driver
    #     url: jdbc:postgresql://localhost:5433/postgres?currentSchema=market
    #     username: postgres
    #     password: postgre
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        #         dialect: org.hibernate.dialect.PostgreSQL94Dialect
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false